### ISSUE TITLE
[Feature] Add tuple operator

### ISSUE THREAD

**Issue by Feliix42** [ohua-dev/ohua-core#6]

**Comment by sertel** [comment]
If we add a `(,)` operator/fn then we should also add `fst` and `snd`.

**Comment by JustusAdam** [comment]
I am not sure about that. `(,)` works different than the equivalent in haskell. It is (currently) multiple arity and creates any kind of tuple. Aka `(,) a b c` creates `(a,b,c)`.

Maybe we shouldn't add something like `fst` but instead a static indexer like `ohua.lang/0` to get the `0`'th element `ohua.lang/1` for the first element. These would not be available to the user, but created by the compiler when desugaring destructuring.

**Comment by sertel** [comment]
Where do we need a multi-arity `(,)` in the compiler?

**Comment by JustusAdam** [comment]
Well, its what the parser creates anytime a user writes `(a, b, c)`.
In particular this is necessary if a user writes an algo that returns multiple values.

For instance 

```hs
let res = smap (\ a -> (sf1 a, sf2 a, sf3 a)) coll
in res2 = smap (\ (a, b, c) -> ... ) res
in ...
```

In this case the first lambda desugars to 

```hs
\a -> 
let a0 = sf1 a in
let a1 = sf2 a in
let a2 = sf3 a
in (,) a0 a1 a2
```

**Comment by JustusAdam** [comment]
If you want I can change the the parser to create `(,)`, `(,,)`, `(,,,)` etc. It may in fact be better to do that ... not sure.

**Comment by sertel** [comment]
This is not quite what I meant. As you point out yourself, this is "use"-code. As such, normally the user would have to provide the according stateful functions.

With the above, it seems that we added support for tuples to our algo language or at least to our standard library. Which means, we *force* each integration to implement these stateful functions.

It seems not such a big deal though.

But if we do then I would like to clarify the relationship between
`ohua.lang/scope`
`ohua.lang/array`
and the various incarnations of
`ohua.lang/(,)`

Please note that a multi-arity tuple might not be as trivially implementable as it seems in a statically typed language. For example, it works in Rust only because of Rust macro system. I guess for a language such as Go, this could be a problem.

(Go has var arg support though: https://stackoverflow.com/questions/19238143/does-golang-support-variadic-function#19238249)

**Comment by sertel** [comment]
I implemented our internal version of `nth` in the Rust backend. I don't think we need anything that builds a tuple for now in the compiler.
